Repository Music-Discovery-Web-App/music-discovery, pull requests merged in 2023-10, with the labels that each got.

#69 Temporarily fixed FE CI and updated to correct BE model names
  client/src/components/ResultSidebar/ResultSidebar.tsx
  server/music_discovery/db.sqlite3
  server/music_discovery/setup/__pycache__/__init__.cpython-311.pyc
  server/music_discovery/setup/__pycache__/settings.cpython-311.pyc
  server/music_discovery/setup/__pycache__/urls.cpython-311.pyc
  server/music_discovery/setup/__pycache__/wsgi.cpython-311.pyc
  server/music_discovery/setup/urls.py
  server/music_discovery/stored_search_results/__pycache__/__init__.cpython-311.pyc
  server/music_discovery/stored_search_results/__pycache__/admin.cpython-311.pyc
  server/music_discovery/stored_search_results/__pycache__/apps.cpython-311.pyc
  server/music_discovery/stored_search_results/__pycache__/models.cpython-311.pyc
  server/music_discovery/stored_search_results/__pycache__/results_serializers.cpython-311.pyc
  server/music_discovery/stored_search_results/__pycache__/tests.cpython-311.pyc
  server/music_discovery/stored_search_results/__pycache__/urls.cpython-311.pyc
  server/music_discovery/stored_search_results/__pycache__/views.cpython-311.pyc
  server/music_discovery/stored_search_results/admin.py
  server/music_discovery/stored_search_results/apps.py
  server/music_discovery/stored_search_results/migrations/0001_initial.py
  server/music_discovery/stored_search_results/migrations/0002_alter_storedsearchresults_user.py
  server/music_discovery/stored_search_results/migrations/__init__.py
  server/music_discovery/stored_search_results/migrations/__pycache__/0001_initial.cpython-311.pyc
  server/music_discovery/stored_search_results/migrations/__pycache__/0002_alter_storedsearchresults_user.cpython-311.pyc
  server/music_discovery/stored_search_results/migrations/__pycache__/__init__.cpython-311.pyc
  server/music_discovery/stored_search_results/models.py
  server/music_discovery/stored_search_results/results_serializers.py
  server/music_discovery/stored_search_results/urls.py
  server/music_discovery/stored_search_results/views.py
  server/music_discovery/user_registration/__pycache__/__init__.cpython-311.pyc
  server/music_discovery/user_registration/__pycache__/admin.cpython-311.pyc
  server/music_discovery/user_registration/__pycache__/apps.cpython-311.pyc
  server/music_discovery/user_registration/__pycache__/models.cpython-311.pyc
  server/music_discovery/user_registration/__pycache__/tests.cpython-311.pyc
  server/music_discovery/user_registration/__pycache__/urls.cpython-311.pyc
  server/music_discovery/user_registration/__pycache__/user_serializers.cpython-311.pyc
  server/music_discovery/user_registration/__pycache__/views.cpython-311.pyc
  server/music_discovery/user_registration/admin.py
  server/music_discovery/user_registration/migrations/0001_initial.py
  server/music_discovery/user_registration/migrations/__init__.py
  server/music_discovery/user_registration/migrations/__pycache__/0001_initial.cpython-311.pyc
  server/music_discovery/user_registration/migrations/__pycache__/__init__.cpython-311.pyc
  server/music_discovery/user_registration/models.py
  server/music_discovery/user_registration/templates/user_registration/signup.html
  server/music_discovery/user_registration/tests.py
  server/music_discovery/user_registration/urls.py
  server/music_discovery/user_registration/user_serializers.py
  server/music_discovery/user_registration/views.py
Labels: bug

#70 Commenting out the footer import to solve CI errors
  client/src/App.tsx
Labels: bug

#72 Updated user_registration tests.py to fix model test case
  server/music_discovery/.gitignore
  server/music_discovery/requirements.txt
  server/music_discovery/setup/__pycache__/__init__.cpython-311.pyc
  server/music_discovery/setup/__pycache__/settings.cpython-311.pyc
  server/music_discovery/setup/__pycache__/urls.cpython-311.pyc
  server/music_discovery/setup/__pycache__/wsgi.cpython-311.pyc
  server/music_discovery/setup/settings.py
  server/music_discovery/stored_search_results/__pycache__/__init__.cpython-311.pyc
  server/music_discovery/stored_search_results/__pycache__/admin.cpython-311.pyc
  server/music_discovery/stored_search_results/__pycache__/apps.cpython-311.pyc
  server/music_discovery/stored_search_results/__pycache__/models.cpython-311.pyc
  server/music_discovery/stored_search_results/__pycache__/results_serializers.cpython-311.pyc
  server/music_discovery/stored_search_results/__pycache__/tests.cpython-311.pyc
  server/music_discovery/stored_search_results/__pycache__/urls.cpython-311.pyc
  server/music_discovery/stored_search_results/__pycache__/views.cpython-311.pyc
  server/music_discovery/user_registration/__pycache__/__init__.cpython-311.pyc
  server/music_discovery/user_registration/__pycache__/admin.cpython-311.pyc
  server/music_discovery/user_registration/__pycache__/apps.cpython-311.pyc
  server/music_discovery/user_registration/__pycache__/models.cpython-311.pyc
  server/music_discovery/user_registration/__pycache__/tests.cpython-311.pyc
  server/music_discovery/user_registration/__pycache__/urls.cpython-311.pyc
  server/music_discovery/user_registration/__pycache__/user_serializers.cpython-311.pyc
  server/music_discovery/user_registration/__pycache__/views.cpython-311.pyc
  server/music_discovery/user_registration/tests.py
Labels: bug, enhancement, implement

#74 Added stored_search_results model test and updated tests.py comments
  server/music_discovery/stored_search_results/tests.py
  server/music_discovery/user_registration/tests.py
Labels: enhancement

#76 75 set up routes
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/components/Navbar/Navbar.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/main.tsx
  client/src/routes.tsx
  client/src/views/Contact/Contact.tsx
  client/src/views/Home/Home.tsx
  client/src/views/Login/Login.tsx
  client/src/views/Login/components/LoginCard.tsx
  client/src/views/Login/components/LoginForm.tsx
  client/src/views/Register/Register.tsx
  client/src/views/Register/components/RegistrationCard.tsx
  client/src/views/Register/components/RegistrationForm.tsx
  package-lock.json
Labels: enhancement, design, implement

#77 User Creation and Login Setup
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/shared/Context/context.types.ts
  client/src/views/Login/Login.tsx
  client/src/views/Login/components/LoginForm.tsx
  package-lock.json
  server/music_discovery/.gitignore
  server/music_discovery/db.sqlite3
  server/music_discovery/requirements.txt
  server/music_discovery/setup/settings.py
  server/music_discovery/setup/urls.py
  server/music_discovery/stored_search_results/admin.py
  server/music_discovery/stored_search_results/models.py
  server/music_discovery/stored_search_results/results_serializers.py
  server/music_discovery/stored_search_results/serializers.py
  server/music_discovery/stored_search_results/tests.py
  server/music_discovery/stored_search_results/urls.py
  server/music_discovery/stored_search_results/views.py
  server/music_discovery/user_registration/admin.py
  server/music_discovery/user_registration/models.py
  server/music_discovery/user_registration/serializers.py
  server/music_discovery/user_registration/templates/user_registration/signup.html
  server/music_discovery/user_registration/tests.py
  server/music_discovery/user_registration/urls.py
  server/music_discovery/user_registration/user_serializers.py
  server/music_discovery/user_registration/views.py
Labels: enhancement, implement

#83 created user registration
  client/src/views/Login/Login.tsx
  client/src/views/Login/components/LoginCard.tsx
  client/src/views/Login/components/LoginForm.tsx
  client/src/views/Register/Register.tsx
  client/src/views/Register/components/RegistrationCard.tsx
  client/src/views/Register/components/RegistrationForm.tsx
  server/music_discovery/db.sqlite3
  server/music_discovery/user_registration/serializers.py
  server/music_discovery/user_registration/views.py
Labels: enhancement, implement

#84 Created generic card component
  client/src/shared/components/Card.tsx
  client/src/views/Contact/Contact.tsx
  client/src/views/Contact/components/ContactCard.tsx
  client/src/views/Contact/components/ContactForm.tsx
  client/src/views/Login/Login.tsx
  client/src/views/Login/components/LoginCard.tsx
  client/src/views/Login/components/LoginForm.tsx
  client/src/views/Register/Register.tsx
  client/src/views/Register/components/RegistrationCard.tsx
  client/src/views/Register/components/RegistrationForm.tsx
Labels: enhancement, implement

#92 Added generic button component
  client/src/shared/components/Button.tsx
  client/src/shared/components/Card.tsx
  client/src/views/Home/Home.tsx
  client/src/views/Login/components/LoginForm.tsx
  client/src/views/Register/components/RegistrationForm.tsx
Labels: enhancement

#94 Added basic setup for UserContext for login and logout
  client/src/components/Navbar/Navbar.tsx
  client/src/routes.tsx
  client/src/shared/Context/context.types.ts
  client/src/shared/context/UserContext.tsx
  client/src/views/Home/Home.tsx
  client/src/views/Login/components/LoginForm.tsx
  client/src/views/Logout/Logout.tsx
Labels: enhancement

#100 Login logout state and backend updates
  client/src/components/Navbar/Navbar.tsx
  client/src/views/Login/components/LoginForm.tsx
  client/src/views/Logout/Logout.tsx
  client/src/views/Register/components/RegistrationForm.tsx
  server/music_discovery/db.sqlite3
  server/music_discovery/requirements.txt
  server/music_discovery/setup/settings.py
  server/music_discovery/user_registration/admin.py
  server/music_discovery/user_registration/models.py
  server/music_discovery/user_registration/serializers.py
  server/music_discovery/user_registration/urls.py
  server/music_discovery/user_registration/views.py
Labels: bug, enhancement
